### ISSUE TITLE
css conflict with default lightboxCssClass

### ISSUE THREAD

**Issue by MarcoWilli** [joppnet/jn_lighterbox#1]
After enabling the extension the image-links on the page got the class "lightbox" which is set by default by  constant styles.content.imgtext.linkWrap.lightboxCssClass (only in my installation?). This leads to faulty layouts because the extension css uses the same class for the lightbox effect.

I changed the lightboxCssClass to something different which works for me but I guess this should not be necessary at all?!

Kind regards

**Comment by AlphawolfWMP** [comment]
Hi Marco,

the jn_lighterbox extension actually uses the CSS class "jnlightbox" so it shouldn't collide with the default class "lightbox". Which version of the extension are you running?

**Comment by MarcoWilli** [comment]
I´m using version 1.0.2.
When I delete lightBoxCssClass from constants it defaults to "lightbox". Doesn´t this come from the core?

**Comment by AlphawolfWMP** [comment]
Hi @MarcoWilli, sorry for the late reply, but I've been quite busy.

So, you're right that the `lightBoxCssClass` constant is set to `lightbox` per default.
![Constants](http://screens.schloebe.de/image_2017-10-20_19_11_50_001.png)

However, as the plugin is resetting some of the default `imageLinkWrap`'s objects, it won't add the default `lightBoxCssClass` to the links generated by the `jn_lighterbox` extension. Here's the markup generated by a click-enlarge image in a fresh TYPO3 8.7.6 installation with the `jn_lighterbox` extension installed which add the `jnlightbox` class but none else for me:
![Markup](http://screens.schloebe.de/image_2017-10-20_19_10_55_001.png)

How does your markup look like without changing the value of `lightboxCssClass`?

**Comment by jumping-blueberry** [comment]
Hi, I have the same issue.
I'm using Typo3 8.7.10 and jn_lighterbox 1.1.0

I changed styles.content.textmedia.linkWrap.lightboxCssClass to jnlightbox.
But this doesn't apply.
The lightbox itself works but the small picture is floating in the text anymore.

I work with FLUID. Could this be an issue?

mfG
jumping-blueberry

**Comment by OliverSchloebe** [comment]
Hi @jumping-blueberry, `styles.content.textmedia` does only apply for "Text w/ Media" CEs. In order to change the class name for "Text w/ Images" CEs, have you tried `styles.content.imgtext.linkWrap.lightboxCssClass`?

**Comment by jumping-blueberry** [comment]
Okay.. thank you! imgtext helped... now the class is applied to the a-tag
styles.content.imgtext.linkWrap {
  lightboxEnabled = 1
  lightboxRelAttribute = lightbox{field:uid}
  lightboxCssClass = jnlightbox
}

But... when I click the link, the picture just opens _top and not in a lightbox.
Do I need to add some more javascript?

**Comment by OliverSchloebe** [comment]
Have you included the extension's static template? It adds some additional JS and CSS files: https://github.com/joppnet/jn_lighterbox/blob/master/Configuration/TypoScript/setup.txt

**Comment by jumping-blueberry** [comment]
yes I included the template:
![bildschirmfoto 2018-07-29 um 16 45 02](https://user-images.githubusercontent.com/40266835/43367539-e0a1cb86-934e-11e8-8b54-6441e64a4908.png)
and this seems to work as well:
![bildschirmfoto 2018-07-29 um 16 46 58](https://user-images.githubusercontent.com/40266835/43367552-175754b6-934f-11e8-9c37-5c2b7297bcf0.png)

**Comment by OliverSchloebe** [comment]
Do you see any errors popping up in your browser's dev console? Maybe jQuery is not loaded?

**Comment by jumping-blueberry** [comment]
I can't see anything in the console since the image loads over the image is loaded.
But jQuery is included:
![bildschirmfoto 2018-07-29 um 16 52 00](https://user-images.githubusercontent.com/40266835/43367595-cebcf6e2-934f-11e8-8faf-208280d08192.png)

**Comment by OliverSchloebe** [comment]
May you please provide a link to your site so I can have a look? :)

**Comment by jumping-blueberry** [comment]
Ich schick's dir per Mail an die Adresse, die im Quelltext steht ;-)

**Comment by jumping-blueberry** [comment]
First, my Apologies for writing German before…
Thank you for the tip. Now it works!

Mit freundlichen Grüßen
Steffi Alvarez
--
Steffi Alvarez
Grafik- und Webdesign
Kapellenweg 10
83416 Saaldorf-Surheim
Tel: 08654/5893822
Fax: 08654/3097971
E-Mail: steffi-alvarez@gmx.de <mailto:steffi-alvarez@gmx.de>

**Comment by OliverSchloebe** [comment]
@jumping-blueberry Kein Problem wegen Deutsch. Ich bin nur wieder auf Englisch gewechselt in der Hoffnung, dass dadurch ggf. auch andere Nutzer hierdurch eine Lösung finden, wenn sie das selbe Problem haben. Und Englisch verstehen eben mehr Leute. :-)

Schön, dass das Problem behoben ist! 👍
