### ISSUE TITLE
lib.contentElement.settings.media.popup.width

### ISSUE THREAD

**Issue by netfeld** [joppnet/jn_lighterbox#10]
Danke für das Plugin! 
Gibt es einen Grund für das Löschen der Default-Dimension des Popups? Das ist doch recht schön, 
die Maximalwerte mit den Defaults setzen zu können. Nach dem 

`lib.contentElement.settings.media.popup.width >` 

habe ich die unreduzierten Original-Bilder in der Lightbox. Und je nachdem wie die Redakteure so ticken kommt das direkt auf einer 20MP Kamera. 

Das ist ein unschöner Site-Effekt!

**Comment by oliverschloebe** [comment]
Hi @netfeld, thanks for the heads-up! Fixed with 1.2.1. ✌️
