### ISSUE TITLE
$_EXTKEY undefined in ext_emconf.php

### ISSUE THREAD

**Issue by drogu02** [joppnet/jn_lighterbox#15]
![image](https://github.com/joppnet/jn_lighterbox/assets/43148349/bf515161-3978-4a6f-9e2e-9b9b1f0d523e)

**Comment by oliverschloebe** [comment]
I'm assuming this is happening in TYPO3 v12?

**Comment by drogu02** [comment]
yes typo3 12!

**Comment by oliverschloebe** [comment]
Fixed in https://github.com/joppnet/jn_lighterbox/commit/84ac0edbf590febb577f1afb8267a3ef1578ad35

Happy Easter! 🐇
