### ISSUE TITLE
Image only opens in the image file

### ISSUE THREAD

**Issue by MRothenburger** [joppnet/jn_lighterbox#17]
Hi,
unfortunately the lightbox no longer works for me after upgrading from typo3 9 to 12. I have the latest version of the extension 1.3.1 
I have entered the following in the typoscript: lib.contentElement.settings.media.popup {
  JSwindow = 0
  crop >
  height >
  width >
  linkParams.ATagParams.dataWrap = class="jnlightbox" rel="lightbox[lb{field:uid}]"
  directImageLink = 1
}

But I already had this in the 9 version. I also activated jquery to rule this out as a problem, but it still doesn't work. Do I need to make any other settings here?

https://upgrade-neu.pulsgetriebe.de/branchen/bergbau.html

Thanks in advanced,
Kind regards, Martina

**Comment by oliverschloebe** [comment]
Hi Martina,

I'm getting error messages in the dev console meaning it couldn't load some of the styles and scripts. Maybe that could be the issue here?

![2024-04-23 12 32 03](https://github.com/joppnet/jn_lighterbox/assets/82846/7eb4c6e0-16b0-4e13-a2d4-99374687d944)

**Comment by MRothenburger** [comment]
Hi Oliver,
thanks for the quick feedback.
Ok I don't know how to fix this, but I will have a look maybe it is because of that. :)

Thanks!

**Comment by MRothenburger** [comment]
I managed to do it, I had to activate the following in hatccess


<FilesMatch "\.js\.gz">
	AddType "text/javascript" .gz
</FilesMatch>
<FilesMatch "\.css\.gz">
	AddType "text/css" .gz
</FilesMatch>
AddEncoding x-gzip .gz

Thanks for your tip!

Thanks :)
