### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by BoresXP** [joppnet/jn_lighterbox#2]
Hello
Typo3 8.7.17
jn_lighterbox 1.1.0
Fluid styled content, fluid styled content CSS and ln_lighterbox static templates included.
Images element on page with Enlarge on click enabled.

Image is still opened in _top. No special styles on image links.

**Comment by OliverSchloebe** [comment]
Hi @BoresXP, have you checked #1 or, more specifically https://github.com/joppnet/jn_lighterbox/issues/1#issuecomment-408681887 setting `styles.content.imgtext.linkWrap`?

**Comment by BoresXP** [comment]
Thanks for answering so fast.
Yes, I have it in my root template, please see screenshot.
![screen1](https://user-images.githubusercontent.com/18707586/43541728-c60d2568-95d3-11e8-9cd0-e0cdcc641656.jpg)
But link in Images element will have no special styles. You can find it here:
http://new.rozslonenok.ru/documents/

**Comment by BoresXP** [comment]
For Typo3 v8 (and v9) with fluid enabled you have to do it this way:
```
lib.contentElement.settings.media.popup {
  JSwindow = 0
  crop >
  height >
  width >
  linkParams.ATagParams.dataWrap = class="jnlightbox" rel="lightbox[lb{field:uid}]"
  directImageLink = 1
}
```
Please correct you setup.ts and add couple of words to extension manual. Don't leave your extension as undocumented piece of (shit) code.

**Comment by OliverSchloebe** [comment]
Thanks @BoresXP, just pushed a new version to the extension repository!
