### ISSUE TITLE
Open images in lightbox from CE not Page

### ISSUE THREAD

**Issue by mschmitz89** [joppnet/jn_lighterbox#5]
If you want to the lightbox to open only the images of the content element and not the whole page, you can use this TypoScript, to achieve this:

lib.contentElement{
	variables.10 = LOAD_REGISTER
	variables.10.content_uid = TEXT
	variables.10.content_uid.field = uid
	settings.media.popup.linkParams.ATagParams.dataWrap = class="jnlightbox" rel="lightbox[lb{register:content_uid}]" 
	stdWrap.append = RESTORE_REGISTER
}

**Comment by OliverSchloebe** [comment]
Thanks @mschmitz89! Found another solution using `{file:current:uid_foreign}` but thanks for the heads-up!
