### ISSUE TITLE
image in lightbox is not responsive

### ISSUE THREAD

**Issue by blueamerican** [joppnet/jn_lighterbox#6]
TYPO3 8.7.27
jn_lighterbox 1.1.8

**Comment by oliverschloebe** [comment]
Hi @blueamerican, the Lightbox script (https://lokeshdhakar.com/projects/lightbox2/) itself is responsive, even though it doesn't re-calculate the image's width and height on-the-fly, but only once the page has been loaded.

We might switch to another lightbox script soon, but for the time being feel free to load another lightbox script of your liking using `page.includeJSFooter.jnlighterbox = <path-to-script>` and `page.includeCSS.jnlighterbox = <path-to-css>`. ✌️
