### ISSUE TITLE
Lightbox working with tx_news only with data-lightbox attribute

### ISSUE THREAD

**Issue by heaven7** [joppnet/jn_lighterbox#7]
Hi,
i recognized that this extension worked with tx_news only by adding the `data-lightbox` attribute to the a tag in the `MediaImage.html` template.

Just adding the `class="jnlightbox"` (via Typoscript) was not enough.

I'm using Typo3 9.5.7 and tx_news 7.3.1

**Comment by oliverschloebe** [comment]
Hi @heaven7, the `class="jnlightbox"` isn't actually what triggers the lightbox. What's important is the attribute `rel="lightbox"` (or `data-lightbox`) on an `<a>` tag.

Actually this is what the default TypoScript in https://github.com/joppnet/jn_lighterbox/blob/master/Configuration/TypoScript/setup.txt#L35 is supposed to add by default.

Have you added the extension's Static Template?

**Comment by heaven7** [comment]
Sure i did.
I also added the `data-lightbox` attribute manually.

The funny thing is, that the rel attribute is not fully implemented. This is the frontend html:
```html
<a data-lightbox="news" href="/fileadmin/news/swissdimensions/2019_11_06_Swiss_Dimensions.jpg" title="" class="jnlightbox" rel="">
    <img itemprop="image" src="/fileadmin/_processed_/5/d/csm_2019_11_06_Swiss_Dimensions_df88041a3d.jpg" width="282" height="188" alt="">
</a>
```

**Comment by oliverschloebe** [comment]
Just tested on several of our TYPO3 installations running TYPO3 9.5.9 and tx_news 7.3.1 and the frontend HTML for `tx_news` media elements in the frontend news detail view look like this:

```html
<a href="/fileadmin/inhalte/Aktuelles/Nachrichten/Jubilare2019/03_Jubilare_2019-11-05.JPG" title="" class="news-lightbox" rel="lightbox[myImageSet]">
	<img src="/fileadmin/_processed_/7/8/csm_03_Jubilare_2019-11-05_c8021ffaf9.jpg" width="250" height="167" alt="">
</a>
```

Btw. I just noticed that `plugin.tx_news.settings.detail.media.image.lightbox` does only apply to the news' detail view. Doesn't it work for you in the list or detail view?

Maybe adding
```
plugin.tx_news.settings.list.media.image.lightbox < plugin.tx_news.settings.detail.media.image.lightbox
```
should do the trick and fill the `rel` attribute correctly in the list view.
